# This is the default (distribution) config file
# For local configuration, please create and edit the file "config.yaml",
# this ensures your configuration to endure a update using git pull

# this file is in YAML format
# If you don't know YAML, check https://de.wikipedia.org/wiki/YAML
# or just copy around existing entries

#############################################
# Global config
# used by both honeypot AND backend

# Credentials for authetification
# Used by honeypot AND backend, only one user is supported currently
# In future backend will have a users table and allow multiple users/honeypots
# backend_user: "CHANGEME"
# backend_pass: "CHANGEME"

##############################################
# Honeypot configuration

# Operate a database without a REST-based backend
# useful if you only want to fill the db but not expose a REST-API
use_local_db: false

# URL to which honeypot will connect to to store data
# used only when use_local_db == false
backend:      "http://localhost:5000"

#############################################
# Backend configuration
# NOT used by honeypot in client mode (use_local_db == false)

# sqlalchemy sql connect string
# examples:
# using sqlite: "sqlite:///database.db"
# using mysql:  ""mysql+mysqldb://USER:PASSWORD@MYSQL_HOST/DATABASE_NAME","
sql: "sqlite:///database.db"

# Max connections to sql db, maybe restricted in some scenarios
max_db_conn: 1

# Directory in which samples are stored
sample_dir: "samples"

# Virustotal API key
vt_key:       "GET_YOUR_OWN"
submit_to_vt: false

cuckoo_enabled:  false,
cuckoo_url_base: "http://127.0.0.1:8090"
cuckoo_user:     "user"
cuckoo_passwd:   "passwd"
cuckoo_force:    0

